steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'services/functions/http_function/src'
    args: [
      'gcloud', 'functions', 'deploy',
      'http-function',
      '--gen2',
      '--runtime', 'go122',
      '--region', 'us-west1',
      '--source', '.',
      '--entry-point', 'HelloWorld',
      '--trigger-http',
      '--allow-unauthenticated',
      '--service-account', 'terraform-sa@primeval-wind-420823.iam.gserviceaccount.com',
    ]

options:
  logging: CLOUD_LOGGING_ONLY
