steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'services/functions/http_function'
    entrypoint: gcloud
    args: [
      'functions', 'deploy',
      'http-function',
      '--gen2',
      '--runtime', 'go122',
      '--region', 'us-west1',
      '--source', './src',
      '--entry-point', 'HttpFunction',
      '--trigger-http',
      '--allow-unauthenticated',
      '--service-account', 'terraform-sa@primeval-wind-420823.iam.gserviceaccount.com'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
