steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/run:latest', 'services/run/' ]

images:
  - 'gcr.io/$PROJECT_ID/image-name'

options:
  logging: CLOUD_LOGGING_ONLY
