steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'services/run'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/run:latest', '.' ]

images:
  - 'gcr.io/$PROJECT_ID/run'

options:
  logging: CLOUD_LOGGING_ONLY
