steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'services/run'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/run:latest', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/run:latest' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy',
      'run-service',
      '--image', 'gcr.io/$PROJECT_ID/run:latest',
      '--region', 'us-west1',
      ' --allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/run'

options:
  logging: CLOUD_LOGGING_ONLY
